services:
  mory-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      # Development-friendly: Direct file access and live reload
      - ./app:/app/app
      - ./data:/app/data
      # Optional: Mount Obsidian vault for testing
      - ${HOME}/Documents/Obsidian:/obsidian:ro
    environment:
      # Development optimized settings
      - MORY_DEBUG=${MORY_DEBUG:-true}
      - MORY_HOST=0.0.0.0
      - MORY_PORT=8080
      - MORY_DATA_DIR=/app/data
      - MORY_OBSIDIAN_VAULT_PATH=/obsidian
      # OpenAI API Key (required for semantic search)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # Semantic search settings
      - MORY_SEMANTIC_SEARCH_ENABLED=${MORY_SEMANTIC_SEARCH_ENABLED:-true}
      - MORY_OPENAI_MODEL=${MORY_OPENAI_MODEL:-text-embedding-3-large}
      - MORY_HYBRID_SEARCH_WEIGHT=${MORY_HYBRID_SEARCH_WEIGHT:-0.7}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/api/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # SQLite Web UI for database inspection and debugging
  sqlite-web:
    image: coleifer/sqlite-web
    ports:
      - "8081:8080"
    volumes:
      - ./data:/data
    command: ["sqlite_web", "/data/memories.db", "--host", "0.0.0.0", "--port", "8080"]
    depends_on:
      - mory-server
    profiles:
      - debug