name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.11'
  UV_CACHE_DIR: /tmp/.uv-cache

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}
        
    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-
          
    - name: Install dependencies
      run: |
        uv sync --extra dev
        uv pip install pytest-cov
        
    - name: Run tests
      run: |
        uv run pytest tests-python/ -v
        
    - name: Run tests with coverage
      run: |
        uv run pytest tests-python/ -v --cov=src/mory --cov-report=xml --cov-report=term-missing
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml

  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}
        
    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-
          
    - name: Install dependencies
      run: |
        uv sync --extra dev --no-install-project
        
    - name: Run ruff linter
      run: |
        uv run ruff check src tests-python
        
    - name: Run ruff formatter check
      run: |
        uv run ruff format --check src tests-python

  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    needs: [test, lint]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}
        
    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-
          
    - name: Install dependencies
      run: |
        uv sync --extra dev
        
    - name: Run quality checks
      run: |
        make quality
        
    - name: Test package installation
      run: |
        uv run python -c "import src.mory; print('✓ Package import successful')"
        
    - name: Test main entry point
      run: |
        timeout 10s uv run python main.py || echo "✓ Main entry point working (timeout expected)"

  build:
    name: Build & Package
    runs-on: ubuntu-latest
    needs: [quality]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        
    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}
        
    - name: Build Python package
      run: |
        uv build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mory-python-package
        path: |
          dist/*.whl
          dist/*.tar.gz
        retention-days: 7